/**
 * @file themes/presets.ts
 * @package @cannasaas/ui
 *
 * All 10 built-in theme presets.
 * Each has 14 color tokens + dark flag + metadata for the Theme Designer.
 */

export interface ThemeColors {
  primary: string;
  secondary: string;
  accent: string;
  bgPrimary: string;
  bgSecondary: string;
  bgCard: string;
  textPrimary: string;
  textSecondary: string;
  sidebarBg: string;
  sidebarText: string;
  success: string;
  warning: string;
  error: string;
  info: string;
  isDark: boolean;
}

export interface ThemePreset extends ThemeColors {
  id: string;
  label: string;
  description: string;
  /** [primary, accent, background] — quick swatch preview */
  swatches: [string, string, string];
}

export const THEME_PRESETS: Record<string, ThemePreset> = {
  casual: {
    id: 'casual',
    label: 'Casual Earthy',
    description: 'Warm organic greens & parchment — the classic dispensary feel',
    swatches: ['#2a6640', '#c47820', '#f7f2e7'],
    primary: '#2a6640',
    secondary: '#5e9b73',
    accent: '#c47820',
    bgPrimary: '#f7f2e7',
    bgSecondary: '#f0ead8',
    bgCard: '#ffffff',
    textPrimary: '#1a1a16',
    textSecondary: '#3a3a30',
    sidebarBg: '#1e4b31',
    sidebarText: '#5e9b73',
    success: '#27ae60',
    warning: '#d97706',
    error: '#c0392b',
    info: '#2e86ab',
    isDark: false,
  },
  dark: {
    id: 'dark',
    label: 'Dark Luxe',
    description: 'Rich dark luxury — electric sage on deep black',
    swatches: ['#4cbe72', '#d4a030', '#080f0a'],
    primary: '#4cbe72',
    secondary: '#7dd4a0',
    accent: '#d4a030',
    bgPrimary: '#080f0a',
    bgSecondary: '#0c1610',
    bgCard: '#101a12',
    textPrimary: '#f5f2e8',
    textSecondary: '#b8b4a8',
    sidebarBg: '#0a1a0c',
    sidebarText: '#4cbe72',
    success: '#4cbe72',
    warning: '#d4a030',
    error: '#e05555',
    info: '#5eafc4',
    isDark: true,
  },
  regal: {
    id: 'regal',
    label: 'Regal Heritage',
    description: 'Deep jewel tones — burgundy, forest, aged gold on cream',
    swatches: ['#7a2838', '#b8920a', '#f8f4ee'],
    primary: '#7a2838',
    secondary: '#b05868',
    accent: '#b8920a',
    bgPrimary: '#f8f4ee',
    bgSecondary: '#f0ead8',
    bgCard: '#ffffff',
    textPrimary: '#1a1208',
    textSecondary: '#2e2010',
    sidebarBg: '#2e1010',
    sidebarText: '#b05868',
    success: '#2d8a50',
    warning: '#d4880c',
    error: '#a83232',
    info: '#4e7e8f',
    isDark: false,
  },
  modern: {
    id: 'modern',
    label: 'Modern Teal',
    description: 'Clean minimal — bright white, slate, electric teal accent',
    swatches: ['#0a7a6a', '#e85d20', '#f8f9fa'],
    primary: '#0a7a6a',
    secondary: '#40a898',
    accent: '#e85d20',
    bgPrimary: '#f8f9fa',
    bgSecondary: '#f0f2f4',
    bgCard: '#ffffff',
    textPrimary: '#0d1117',
    textSecondary: '#1e2530',
    sidebarBg: '#083028',
    sidebarText: '#40a898',
    success: '#27ae60',
    warning: '#d97706',
    error: '#c0392b',
    info: '#2e86ab',
    isDark: false,
  },
  minimal: {
    id: 'minimal',
    label: 'Minimal',
    description: 'Near-monochrome — ultra-refined editorial luxury',
    swatches: ['#1a1a1a', '#2a7a40', '#fafafa'],
    primary: '#1a1a1a',
    secondary: '#484848',
    accent: '#2a7a40',
    bgPrimary: '#fafafa',
    bgSecondary: '#f4f4f4',
    bgCard: '#ffffff',
    textPrimary: '#141414',
    textSecondary: '#282828',
    sidebarBg: '#141414',
    sidebarText: '#787878',
    success: '#2a7a40',
    warning: '#d97706',
    error: '#c0392b',
    info: '#2e86ab',
    isDark: false,
  },
  citrus: {
    id: 'citrus',
    label: 'Citrus Pop',
    description: 'Bright & energetic — lime greens with punchy orange',
    swatches: ['#5aaa20', '#e87820', '#f8faf4'],
    primary: '#5aaa20',
    secondary: '#88cc50',
    accent: '#e87820',
    bgPrimary: '#f8faf4',
    bgSecondary: '#f0f5e8',
    bgCard: '#ffffff',
    textPrimary: '#1a2010',
    textSecondary: '#2e3c20',
    sidebarBg: '#285010',
    sidebarText: '#88cc50',
    success: '#5aaa20',
    warning: '#e87820',
    error: '#c0392b',
    info: '#2e86ab',
    isDark: false,
  },
  earthy: {
    id: 'earthy',
    label: 'Earthy Classic',
    description: 'Deep forest greens, golden amber, parchment — serif display',
    swatches: ['#2a6640', '#c47820', '#f7f2e7'],
    primary: '#2a6640',
    secondary: '#5e9b73',
    accent: '#c47820',
    bgPrimary: '#f7f2e7',
    bgSecondary: '#f0ead8',
    bgCard: '#ffffff',
    textPrimary: '#1a1a16',
    textSecondary: '#3a3a30',
    sidebarBg: '#1e4b31',
    sidebarText: '#5e9b73',
    success: '#27ae60',
    warning: '#d97706',
    error: '#c0392b',
    info: '#2e86ab',
    isDark: false,
  },
  neon: {
    id: 'neon',
    label: 'Neon Street',
    description: 'Bold streetwear — electric green, hot pink on near-black',
    swatches: ['#00ff78', '#ff2d78', '#0a0a0a'],
    primary: '#00ff78',
    secondary: '#80ffbc',
    accent: '#ff2d78',
    bgPrimary: '#0a0a0a',
    bgSecondary: '#111111',
    bgCard: '#161616',
    textPrimary: '#f0f0e8',
    textSecondary: '#d0d0c8',
    sidebarBg: '#0a0a0a',
    sidebarText: '#00ff78',
    success: '#00ff78',
    warning: '#ffaa00',
    error: '#ff2d78',
    info: '#00aaff',
    isDark: true,
  },
  midnight: {
    id: 'midnight',
    label: 'Midnight Garden',
    description: 'Rich dark luxury — electric sage on deep earth',
    swatches: ['#4cbe72', '#d4a030', '#0e1512'],
    primary: '#4cbe72',
    secondary: '#6b8a7a',
    accent: '#d4a030',
    bgPrimary: '#0e1512',
    bgSecondary: '#162019',
    bgCard: '#1a2820',
    textPrimary: '#e8efe6',
    textSecondary: '#9aaa96',
    sidebarBg: '#080d0a',
    sidebarText: '#7aaa82',
    success: '#4cbe72',
    warning: '#e8a317',
    error: '#e05555',
    info: '#5eafc4',
    isDark: true,
  },
  apothecary: {
    id: 'apothecary',
    label: 'Apothecary',
    description: 'Muted botanical — old-world herbal elegance',
    swatches: ['#4a6741', '#a67c52', '#f5f2ec'],
    primary: '#4a6741',
    secondary: '#8a7e6b',
    accent: '#a67c52',
    bgPrimary: '#f5f2ec',
    bgSecondary: '#ebe6dc',
    bgCard: '#fdfcf8',
    textPrimary: '#2a2820',
    textSecondary: '#6a6458',
    sidebarBg: '#24261e',
    sidebarText: '#b4b0a2',
    success: '#4a7a50',
    warning: '#c48820',
    error: '#a84040',
    info: '#5a7e8a',
    isDark: false,
  },
  verdant: {
    id: 'verdant',
    label: 'Verdant Dusk',
    description: 'Deep forest tones with golden hour warmth',
    swatches: ['#1a5c38', '#d4a24e', '#f7f4ed'],
    primary: '#1a5c38',
    secondary: '#5e8b6a',
    accent: '#d4a24e',
    bgPrimary: '#f7f4ed',
    bgSecondary: '#ece6da',
    bgCard: '#fffef9',
    textPrimary: '#1a1a14',
    textSecondary: '#5c5647',
    sidebarBg: '#0f2b1e',
    sidebarText: '#a3c4a6',
    success: '#2d8a50',
    warning: '#e8a317',
    error: '#b83028',
    info: '#3a7ca5',
    isDark: false,
  },
  terracotta: {
    id: 'terracotta',
    label: 'Terracotta Sage',
    description: 'Warm clay & desert sage — southwestern apothecary',
    swatches: ['#8b5a3c', '#c2662d', '#fdf8f3'],
    primary: '#8b5a3c',
    secondary: '#7a8b6f',
    accent: '#c2662d',
    bgPrimary: '#fdf8f3',
    bgSecondary: '#f3ece2',
    bgCard: '#fffefa',
    textPrimary: '#3a2a1e',
    textSecondary: '#7a6b5c',
    sidebarBg: '#2a1e14',
    sidebarText: '#c4b49e',
    success: '#4a8c5c',
    warning: '#d4880c',
    error: '#a83232',
    info: '#4e7e8f',
    isDark: false,
  },
};

export const PRESET_IDS = Object.keys(THEME_PRESETS);
export type PresetId = keyof typeof THEME_PRESETS;
export const DEFAULT_PRESET: PresetId = 'casual';
