/**
 * useProductFilters — URL-driven filter state via useSearchParams
 *
 * TODO: Replace this stub with the populated version from the zip.
 * This file was auto-generated by scaffold-storefront.sh
 */

export {};
