import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Migration: AddThemeIdToOrganizations
 *
 * Adds `theme_id` column to the `organizations` table.
 * Maps to the GreenStack design system theme files:
 *   packages/ui/src/themes/theme.<id>.css
 *
 * Valid values: 'earthy' | 'midnight' | 'citrus' | 'apothecary' | 'neon'
 * Default: 'earthy'
 *
 * Generated by scaffold-themes.sh
 */
export class AddThemeIdToOrganizations implements MigrationInterface {
  name = 'AddThemeIdToOrganizations';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // Add theme_id with a default so existing rows are valid immediately
    await queryRunner.query(`
      ALTER TABLE "organizations"
      ADD COLUMN IF NOT EXISTS "theme_id" VARCHAR(64)
      NOT NULL DEFAULT 'earthy'
    `);

    // Add a check constraint to prevent invalid theme IDs
    await queryRunner.query(`
      ALTER TABLE "organizations"
      ADD CONSTRAINT "chk_organizations_theme_id"
      CHECK ("theme_id" IN ('earthy', 'midnight', 'citrus', 'apothecary', 'neon'))
    `);

    // Index for fast lookup when resolving tenant branding
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "idx_organizations_theme_id"
      ON "organizations" ("theme_id")
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP INDEX IF EXISTS "idx_organizations_theme_id"
    `);

    await queryRunner.query(`
      ALTER TABLE "organizations"
      DROP CONSTRAINT IF EXISTS "chk_organizations_theme_id"
    `);

    await queryRunner.query(`
      ALTER TABLE "organizations"
      DROP COLUMN IF EXISTS "theme_id"
    `);
  }
}
