/**
 * @file cart-item.ts
 * @package @cannasaas/types
 *
 * Cart and Product variant types that mirror:
 *   GET  /cart
 *   POST /cart/items    → { productId, variantId, quantity }
 *   PUT  /cart/items/:id
 *
 * CartItem is also the shape persisted in Zustand's cartStore
 * (with localStorage serialisation via the `persist` middleware).
 *
 * ProductVariant mirrors the `variants` array in GET /products responses.
 */

// ── Product Variant ───────────────────────────────────────────────────────────

/**
 * A purchasable SKU — one product may have many variants (sizes/weights).
 * e.g. "1/8 oz", "1/4 oz", "1 oz" for a flower product.
 */
export interface ProductVariant {
  id: string;
  productId: string;
  /** Human-readable label displayed in the variant picker UI */
  name: string;
  /** Internal SKU used for inventory and Metrc compliance */
  sku: string;
  /** Weight in grams — used for cannabis purchase limit calculations */
  weight: number;
  /** "g" | "oz" | "mg" | "ml" | "each" */
  weightUnit: string;
  price: number;
  /** Current on-hand quantity — drives "Low stock" badges */
  quantity: number;
  /** When set, the UI caps quantity input at this value */
  maxPurchaseQuantity?: number;
  isActive: boolean;
}

// ── Cart Item ─────────────────────────────────────────────────────────────────

/**
 * A single line item in the shopping cart.
 *
 * Client-side IDs are generated by cartStore:
 *   `${productId}-${variantId}-${Date.now()}`
 *
 * The server-side cart (GET /cart) returns the same shape but with
 * server-generated UUIDs for `id`.
 */
export interface CartItem {
  /** Composite client-side ID (or server UUID after cart sync) */
  id: string;
  productId: string;
  variantId: string;

  /** Denormalised product data — cached client-side to avoid re-fetching */
  productName: string;
  productSlug?: string;
  variantName: string;
  /** Primary product image URL for cart line-item thumbnail */
  imageUrl?: string | null;

  /** Unit price at time of adding to cart */
  unitPrice: number;
  quantity: number;
  /** unitPrice × quantity — computed by backend, stored for display */
  totalPrice: number;

  /** Weight per unit in grams — used for purchase limit validation */
  weightGrams: number;

  /** Compliance: cannabis category affects per-purchase limits */
  category?: string;

  /** If true, item is flagged as medical-only and requires med card */
  requiresMedCard?: boolean;
}

// ── Cart ─────────────────────────────────────────────────────────────────────

/**
 * The full cart response from GET /cart.
 * Also used as the type for the server-side cart sync payload.
 */
export interface Cart {
  id: string;
  userId: string;
  dispensaryId: string;
  items: CartItem[];

  subtotal: number;

  /** Applied promotion details — null if no promo active */
  appliedPromo?: {
    code: string;
    discountAmount: number;
    discountType: 'flat' | 'percentage';
  } | null;

  promoDiscount: number;

  /** Tax calculated server-side based on dispensary state/locality */
  tax: number;
  /** Tax rate as a decimal, e.g. 0.1325 for 13.25% */
  taxRate: number;

  /** Delivery fee — 0 for pickup orders */
  deliveryFee: number;

  total: number;

  /** Whether the cart's total weight exceeds state purchase limits */
  exceedsPurchaseLimit: boolean;
}
