/**
 * ProductGrid — 2-col mobile / 3-col desktop responsive grid
 *
 * TODO: Replace this stub with the populated version from the zip.
 * This file was auto-generated by scaffold-storefront.sh
 */

export {};
